// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Qlyrapchieuphim
{
    using System.Linq;
    using System.Text;
    using System.Data;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ReceiptTemplate : ReceiptTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<body>\r\n    <h2 style=\"text-align: center;\">RẠP PHIM</h2>\r\n    <h1 style=\"text-al" +
                    "ign: center;\">MOVIE-LAND</h1>\r\n    <hr />\r\n    <div style=\"display: flex; justif" +
                    "y-content: space-between;\">\r\n        <p> Hoá đơn số: ");
            
            #line 12 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(billCode));
            
            #line default
            #line hidden
            this.Write("</p>\r\n        <p>Ngày: ");
            
            #line 13 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(createdAt.ToString("dd/MM/yyyy")));
            
            #line default
            #line hidden
            this.Write(" / ");
            
            #line 13 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(createdAt.ToString("HH:mm:ss")));
            
            #line default
            #line hidden
            this.Write("</p>\r\n    </div>\r\n\r\n    <div style=\"display: flex; justify-content: space-between" +
                    ";\">\r\n        <p> Phim: <b>");
            
            #line 17 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(title));
            
            #line default
            #line hidden
            this.Write("</b></p>\r\n        <p>Giờ chiếu: ");
            
            #line 18 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startTime.ToString("dd/MM/yyyy")));
            
            #line default
            #line hidden
            this.Write(" / ");
            
            #line 18 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startTime.ToString("HH:mm:ss")));
            
            #line default
            #line hidden
            this.Write(@"</p>
    </div>
    <table width = ""100%"" runat=""server"" id=""Table1"">
        <thead>
            <tr style=""text-align: left;"">
                <th width = ""10%"">STT</th>
                <th width = ""45%"">Sản phẩm</th>
                <th width = ""15%"">Giá</th>
                <th width = ""15%"">Số lượng </th>
                <th width = ""15%"">Đơn Giá</th>
            </tr>
        </thead>
        <tbody>
            ");
            
            #line 31 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
int i = 1;
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 32 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
foreach (DataRow row in billData.Rows)
            {
            
            #line default
            #line hidden
            this.Write("                <tr>\r\n                    <td> ");
            
            #line 35 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" </td>\r\n                    <td> ");
            
            #line 36 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(row["ProductName"].ToString()));
            
            #line default
            #line hidden
            this.Write(" </td>\r\n                    <td> ");
            
            #line 37 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Convert.ToDouble(row["Price"]).ToString("N2") + " VNĐ"));
            
            #line default
            #line hidden
            this.Write(" </td>\r\n                    <td> ");
            
            #line 38 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(row["Quantity"].ToString()));
            
            #line default
            #line hidden
            this.Write(" </td>\r\n                    <td> ");
            
            #line 39 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Convert.ToDouble(row["TotalPrice"]).ToString("N2") + " VNĐ"));
            
            #line default
            #line hidden
            this.Write(" </td>\r\n                <tr/>\r\n            ");
            
            #line 41 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
i++; 
            } //end of foreach
            
            #line default
            #line hidden
            this.Write("        </tbody>\r\n    </table>\r\n    <hr/>\r\n        <div style=\"justify-content: s" +
                    "pace-between; display:flex\">\r\n            <b>Tổng đơn giá: </b> ");
            
            #line 47 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((totalTickets + totalProducts).ToString("N2") + " VNĐ"));
            
            #line default
            #line hidden
            this.Write("<br/>\r\n        </div>\r\n\r\n        <div style=\"justify-content: space-between; disp" +
                    "lay:flex\">\r\n            <b>Được giảm: </b> ");
            
            #line 51 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(totalDiscount.ToString("N2") + " VNĐ"));
            
            #line default
            #line hidden
            this.Write("<br/>\r\n        </div>\r\n        \r\n\r\n        ");
            
            #line 55 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
if (studentDiscount != 0) 
        {
            
            #line default
            #line hidden
            this.Write("            <div style=\"justify-content: space-between; display:flex\">\r\n         " +
                    "       <b>Giảm giá sinh viên: </b>\r\n                \r\n                ");
            
            #line 60 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((studentDiscount / 15000)));
            
            #line default
            #line hidden
            this.Write(" sinh viên: ");
            
            #line 60 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((-1 * studentDiscount).ToString("N2") + " VNĐ"));
            
            #line default
            #line hidden
            this.Write("\r\n                \r\n            </div>\r\n        ");
            
            #line 63 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 65 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
if (childrenDiscount != 0) 
        {
            
            #line default
            #line hidden
            this.Write("            <div style=\"justify-content: space-between; display:flex\">\r\n         " +
                    "       <b>Giảm giá trẻ em:</b>\r\n                ");
            
            #line 69 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((childrenDiscount / 15000)));
            
            #line default
            #line hidden
            this.Write(" trẻ em: ");
            
            #line 69 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((-1 * childrenDiscount).ToString("N2") + " VNĐ"));
            
            #line default
            #line hidden
            this.Write("\r\n            </div>\r\n        ");
            
            #line 71 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n        <div style=\"justify-content: space-between; display:flex\">\r\n           " +
                    " <b>Tổng: </b> ");
            
            #line 74 "D:\Github_Projects\IT008-LTTQ\Movie-management-system\Qlyrapchieuphim\ReceiptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((totalTickets + totalProducts) - totalDiscount - childrenDiscount - studentDiscount).ToString("N2") + " VNĐ"));
            
            #line default
            #line hidden
            this.Write(" <br/>\r\n        </div>\r\n</body>\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class ReceiptTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
